docker rmi ardiadrianadri/mongo_node_one:1.0.6
docker rmi ardiadrianadri/mongo_node_four:1.0.3
docker rmi ardiadrianadri/mongo_node_three:1.0.3
docker rmi ardiadrianadri/mongo_node_two:1.0.3
docker rmi ardiadrianadri/mongo_node_one:1.0.5
docker rmi ardiadrianadri/mongo_node_four:1.0.2
docker rmi ardiadrianadri/mongo_node_four:1.0.1
docker rmi ardiadrianadri/mongo_node_three:1.0.2
docker rmi ardiadrianadri/mongo_node_three:1.0.1
docker rmi ardiadrianadri/mongo_node_two:1.0.2
docker rmi ardiadrianadri/mongo_node_two:1.0.1
docker rmi ardiadrianadri/mongo_node_one:1.0.4
docker rmi ardiadrianadri/mongo_node_one:1.0.3
docker rmi ardiadrianadri/mongo_node_one:1.0.2
docker rmi ardiadrianadri/mongo_node_one:1.0.1
docker rmi ardiadrianadri/mongo_node_four:1.0.0
docker rmi ardiadrianadri/mongo_node_three:1.0.0
docker rmi ardiadrianadri/mongo_node_two:1.0.0
docker rmi ardiadrianadri/mongo_node_one:1.0.0
docker rmi ardi/volumentest:1.0  
docker rmi tomcat:lates
docker rmi tomcat:7    
docker rmi nginx:lates
docker rmi centos:7    
docker rmi ubuntu:14.04
docker rmi quay.io/letsencrypt/letsencrypt:lates
docker rmi hello-world:lates